spring:
  application:
    name: ards

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      ds1:
        url: jdbc:mysql://localhost:3307/spring-boot-demos?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
#      ds2:
#        url: jdbc:mysql://localhost:3307/spring-boot-demos?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
#        username: root
#        password: password
#        driver-class-name: com.mysql.cj.jdbc.Driver

      min-idle: 5 # 最小连接数
      initial-size: 5
      max-active: 100 # 最大连接数
      max-wait: 60000 # 配置获取连接等待超时的时间 (毫秒）
