// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package org.relaxcg.grpc.proto;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * 电话号码
   * </pre>
   *
   * <code>int32 phoneNumber = 2;</code>
   */
  int getPhoneNumber();

  /**
   * <pre>
   * 邮箱地址
   * </pre>
   *
   * <code>string email = 3;</code>
   */
  String getEmail();
  /**
   * <pre>
   * 邮箱地址
   * </pre>
   *
   * <code>string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <pre>
   * 序列号
   * </pre>
   *
   * <code>int32 serialNumber = 4;</code>
   */
  int getSerialNumber();
}
