// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package org.relaxcg.grpc.proto;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
