
server:
  port: 9000

spring:
  servlet:
    multipart:
      location: C:/Users/gaocheng/Documents/uploads
#spring:
#  web:
#    resources:
#      static-locations: classpath:/static/,classpath:/resources/
