server:
  servlet:
    context-path: /payment
  port: 9205

spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3307/shopping-centre?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.relaxcg.sc.order.mapper: debug